### ISSUE TITLE
Remove call to deprecated function "vscode.previewHtml"

### ISSUE THREAD

**Issue by TAGC** [jmazouri/SharpPad#6]
I have the latest public version of SharpPad installed (v1.0.5). On running the command "Show SharpPad window", I get the following warning popup:

> Extension 'jmazouri.sharppad' uses the 'vscode.previewHtml' command which is deprecated and will be removed soon. Please file an issue against this extension to update to use VS Code's webview API.

It seems that the call is made here:

https://github.com/jmazouri/SharpPad/blob/cfd56c98bce70e9de8bf3fe9b1b5a5fd2c987d2d/SharpPad.VSCode/src/extension.ts#L21-L23

**Comment by jmazouri** [comment]
Thanks for the report! I've fixed this issue as of 1.1.0 (the latest commit), and will make a new release ASAP.
