### ISSUE TITLE
Duplicates of usings in metadata

### ISSUE THREAD

**Issue by Jeidoz** [jmazouri/SharpPad#8]
Hi, I just installed SharpPad Extension for the first time on VS Code. Went by reference on type "int" (F12) as was written in a book ("_C# 8.0 and .NET Core 3.0 – Modern Cross-Platform Development Fourth Edition published by Packt_"). And got using duplicates:

![image](https://user-images.githubusercontent.com/23425714/70381837-27944180-195a-11ea-8aa9-0217b271c0ad.png)

_Is it the problem of extension or just on my side (OS/VS Code/etc.)?_

**Project type**: Console App (.NET Core v3.0)

**Info about my VS Code:**
```
VS Code Version: 1.40.2 (user setup)
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:54:45.096Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

```

**Info about my Windows:**
```
Edition: Windows 10 Pro
Version: 1909
Installed on: 30-Sep-19
OS Build: 18363.476
```

**Comment by TAGC** [comment]
I'm not the maintainer but is SharpPad the only extension you have installed, or do you have the [C# Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.csharp) installed as well?

If the latter, have you tried uninstalling the SharpPad extension and seeing if you can reproduce the issue?

**Comment by Jeidoz** [comment]
Yeah, I have C# Extension. I tried to disable/enable and reinstall some extensions, and it was fixed. I think the problem was in incorrect plugins load/install order or some type of it.
